/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Paul (https://sketchfab.com/paul_paul_paul)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/free-skybox-anime-sky-56a60c1d1e8b44eabff138374f996d8f
Title: FREE - SkyBox Anime Sky
*/

import { useGLTF } from '@react-three/drei'
import React, { useRef, useEffect } from 'react'
import skyScene from '../assets/3d/sky.glb'

const Sky = (props) => {
  const skyRef = useRef()
  const { scene } = useGLTF(skyScene)

  // Mouse movement effect
  useEffect(() => {
    const handleMouseMove = (event) => {
      if (skyRef.current) {
        const { innerWidth, innerHeight } = window
        const mouseX = (event.clientX / innerWidth) * 2 - 1
        const mouseY = -(event.clientY / innerHeight) * 2 + 1

        skyRef.current.rotation.y = mouseX * 0.2 // Adjust sensitivity as needed
        skyRef.current.rotation.x = mouseY * 0.2 // Adjust sensitivity as needed
      }
    }

    window.addEventListener('mousemove', handleMouseMove)

    return () => {
      window.removeEventListener('mousemove', handleMouseMove)
    }
  }, [])

  return (
    <mesh ref={skyRef} {...props}>
      <primitive object={scene} />
    </mesh>
  )
}

export default Sky
